server {
    listen 80;
    listen [::]:80;
    server_name 164.90.219.7;

    return 301 http://mangotreeofficial.com$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name mangotreeofficial.com www.mangotreeofficial.com;

    root /var/www/mango-tree; 
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}