services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - app-tier

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    expose:
      - "3000"
    networks:
      - app-tier

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    expose:
      - "80"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge