services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
      - /app/backend/dist
      - ./shared:/app/shared

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - .env
    ports:
      - "5173:80"
